name: Build

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 10 * * 1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      name: Setup Node
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: |
        npm i
    - name: Run Tests
      run: |
        CI=true npm run test

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      name: Setup Node
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: |
        npm i
    - name: Run Lint
      run: |
        npm run lint

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      name: Setup Node
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: |
        npm i
    - name: Run Deploy
      run: |
        npm run deploy
